; PlatformIO Project Configuration File

[env:d1]
platform = espressif8266
board = d1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
; upload_port = 192.168.11.232
; upload_protocol = espota
lib_deps =
	fastled/FastLED@^3.5.0
	adafruit/Adafruit SSD1306@^2.5.7
	adafruit/Adafruit GFX Library@^1.11.5
	olkal/HX711_ADC@^1.2.12
	tzapu/WiFiManager@^2.0.17
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.0.0
